
orderRpc:
	cd service/order/rpc && go run order.go

productRpc:
	cd service/product/rpc && go run product.go

userRpc:
	cd service/user/rpc && go run user.go

payRpc:
	cd service/pay/rpc && go run pay.go






orderApi:
	cd service/order/api && go run order.go

productApi:
	cd service/product/api && go run product.go

userApi:
	cd service/user/api && go run user.go

payApi:
	cd service/pay/api && go run pay.go